### PR TITLE
Rebase on top of Halo2 version 0.3.0

### PR DESCRIPTION
**Pull request by bazzilic**
Our fork was rebased on top of commit https://github.com/zcash/halo2/commit/263356784042d7d4c1c17d357c94c1acaeb75ab5, which is the commit of v0.3.0.
All tests pass.
Closes https://github.com/anoma/taiga/issues/154

### CODE REVIEW

**Comment by XuyangSong** [comment]
Taiga doesn't compile if I use the `vasily/update` branch as the patch.
Do we also need some updates in taiga?

**Comment by XuyangSong** [comment]
We probably need to update the pasta_curves lib.

**Comment by bazzilic** [comment]
Do we use our own fork of the lib as well?

**Comment by XuyangSong** [comment]
> Do we use our own fork of the lib as well?

yes. pasta_curves = { git="https://github.com/heliaxdev/pasta_curves", branch="taiga"}

**Comment by bazzilic** [comment]
Hm, so I checked. Halo2 in this PR uses pasta_curves v0.4.0, `taiga` branch of https://github.com/heliaxdev/pasta_curves is up to date with v0.4.0 too. It's actually v0.4.1 I think based on the commit history.

**Comment by XuyangSong** [comment]
That could be other dependency problems.

**Comment by bazzilic** [comment]
I'll investigate further.

**Review by XuyangSong — APPROVED** [review]
lgtm

**Pull request merged**
