### PR TITLE
Add vk serialisation

### PR DESCRIPTION
**Pull request by Acentelles**
Picking up changes from https://github.com/privacy-scaling-explorations/halo2/pull/103

### CODE REVIEW

**Comment by XuyangSong** [comment]
Could you please merge it to the `taiga` branch?

**Comment by Acentelles** [comment]
Done @XuyangSong

**Comment by bazzilic** [comment]
LGTM! Two things:

1. A request! Considering all the potential issues with this in the future when this refactoring takes place in the main Halo2 codebase, can you please add an end-to-end test where you create a circuit, serialize the VK (just to a buffer), de-serialize it back, and then you can produce a valid and an invalid proof. So when we merge updates from the main Halo codebase, we can detect if something goes wrong here.

2. A question! What is a better strategy for future maintainability of the code divergence: 1) merge this changes into `taiga` branch; or 2) create a `taiga+serde` branch and keep rebasing it on top of `taiga`?

**Comment by XuyangSong** [comment]
lgtm
1. There is a test in the halo2_proofs/examples/serialization.rs @bazzilic

**Review by XuyangSong — APPROVED** [review]

**Comment by Acentelles** [comment]
@bazzilic keeping a `taiga-serde` branch sounds like a good idea to me but I don't know if it is worth the overhead. I would merge this work into `taiga` directly

**Comment by bazzilic** [comment]
@XuyangSong would this test in the example execute when we do `cargo test` for the whole project?
PS: I don't see the test there, only the example itself.

**Comment by XuyangSong** [comment]
> @XuyangSong would this test in the example execute when we do `cargo test` for the whole project? PS: I don't see the test there, only the example itself.

No, I guess they don't want to create a file whenever running the `cargo test`. So they put the test in an example.
In general, the examples will also be tested/executed automatically by CI when pushing and merging. But we don't open the CI since we only made minor modifications.
Anyway, it's OK to add a separate test for it.

**Comment by bazzilic** [comment]
Yeah, creating a file during testing is not great, but you can ser-de to-from a buffer without writing it to a file. Anyway, this looks good, maybe we can add a test at some point later.

**Pull request merged**
